export const types = Object.freeze({
    START_FETCHING:    'START_FETCHING',
    STOP_FETCHING:     'STOP_FETCHING',
    EMIT_ERROR:        'EMIT_ERROR',
    SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
    HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
    SET_ONLINE_STATE:  'SET_ONLINE_STATE',
    SET_OFFLINE_STATE: 'SET_OFFLINE_STATE',
});
