export const types = Object.freeze({
    // Sync
    INITIALIZE:   'INITIALIZE',
    AUTHENTICATE: 'AUTHENTICATE',
    LOGOUT:       'LOGOUT',
    VALID:        'VALID',
    REGISTERED:   'REGISTERED',

    // Async
    INITIALIZE_ASYNC:       'INITIALIZE_ASYNC',
    LOGIN_ASYNC:            'LOGIN_ASYNC',
    AUTHENTICATE_ASYNC:     'AUTHENTICATE_ASYNC',
    LOGOUT_ASYNC:           'LOGOUT_ASYNC',
    SIGNUP_ASYNC:           'SIGNUP_ASYNC',
    CONFIRM_SIGNUP_ASYNC:   'CONFIRM_SIGNUP_ASYNC',
    ACTIVATE_ACCOUNT_ASYNC: 'ACTIVATE_ACCOUNT_ASYNC',
});
